[package]
name = "flowrs"
version = "0.0.1"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
chrono = "0.4"

[lib]
crate-type = ["cdylib"]  # Required for Python extensions

[package.metadata.maturin]
bindings = "pyo3"
