name: Python Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    # Step 3: Set up Python environment (Python 3.x)
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.13.1

    # Step 4: Install maturin
    - name: Install maturin
      run: |
        python -m pip install --upgrade pip
        pip install maturin

    # Step 5: Build the Rust extension with maturin
    - name: Build Rust extension
      run: |
        cd flowrs
        maturin build --release
        WHEEL_FILE=$(ls target/wheels/*.whl | head -n 1)
        pip install --force-reinstall "$WHEEL_FILE"

    # Step 6: Run Python tests
    - name: Run tests
      run: |
        python -m unittest discover tests
